### ISSUE TITLE
还是有个小瑕疵

### ISSUE THREAD

**Issue by hqzh** [luciojs/tree-transfer#12]
```js
import React, { Component } from 'react';
import TreeTransfer from 'antd-tree-transfer';

const source = [
  {
    key: '0',
    title: '0',
    children: [
      {
        key: '0-0',
        title: '0-0',
      },
      {
        key: '0-1',
        title: '0-1',
      }
    ]
  },
{
    key: '1',
    title: '1',
//里面的上面的一样
    children: [
      {
        key: '0-0',
        title: '0-0',
      },
      {
        key: '0-1',
        title: '0-1',
      }
    ]
  }
],

class App extends Component {
  state = {
    target: ['0-1']
  }

  handleChange = (target) => {
    this.setState({
      target
    });
  }

  render() {
    return <TreeTransfer source={source} target={this.state.target} onChange={this.handleChange}>
  }
}

render(<App />, document.querySelector('#app'));
```
不正常
![1](https://user-images.githubusercontent.com/26128706/59329428-6a65bb80-8d21-11e9-8347-c16b1815d704.png)
不正常
![2](https://user-images.githubusercontent.com/26128706/59329435-6e91d900-8d21-11e9-9338-b59666fb9fc4.png)
正常
![3](https://user-images.githubusercontent.com/26128706/59329444-72256000-8d21-11e9-8e9f-0e9687b97742.png)

_Originally posted by @hqzh in https://github.com/jindada/tree-transfer/issues/10#issuecomment-501106180_

**Comment by jindada** [comment]
图都裂了 可以文字描述或者提供个在线例子吗

**Comment by hqzh** [comment]
就是两个分组选项都一样的情况下，勾选其中一个的全选，另一个全选也应该勾上。
![1](https://user-images.githubusercontent.com/26128706/59478605-7de16580-8e8c-11e9-89b6-493c0c3266ac.png)
![2](https://user-images.githubusercontent.com/26128706/59478612-8174ec80-8e8c-11e9-8767-a1b04c1801a6.png)
![3](https://user-images.githubusercontent.com/26128706/59478615-846fdd00-8e8c-11e9-8ea9-d6762f543b61.png)

**Comment by jindada** [comment]
我感觉这个是合理的 2个分组下面的人是同一个key  所以都会勾选上

**Comment by hqzh** [comment]
都会勾选上是合理。现在是不会都勾选上
不正常
![1](https://user-images.githubusercontent.com/26128706/59491536-84d29d00-8eb9-11e9-8230-7b3dac86c7d8.png)
不正常
![2](https://user-images.githubusercontent.com/26128706/59491554-8d2ad800-8eb9-11e9-80da-545d799e8caf.png)
正常
![3](https://user-images.githubusercontent.com/26128706/59491566-9320b900-8eb9-11e9-81e1-500aa5498699.png)

**Comment by jindada** [comment]
确实有问题 后续修复 也欢迎pr
