### ISSUE TITLE
打包后体积太大

### ISSUE THREAD

**Issue by hqzh** [luciojs/tree-transfer#13]
本项目打包后的体积比antd的体积还大。

**Comment by jindada** [comment]
这个确实发现了 后续会修改 打包程序是自己很早之前写的 有些问题

**Comment by hqzh** [comment]
应该是webpack没配置好吧，我没看到这个项目的打包命令

**Comment by jindada** [comment]
没用webpack 是自己基于webpack写的打包程序

**Comment by jindada** [comment]
用babel直接编译就行 你可以自己改一下

**Comment by hqzh** [comment]
"eslint.autoFixOnSave": true,
    "eslint.workingDirectories": [
        ".eslintrc",
    ],
    "eslint.options": {
        "extensions": [".js",".vue"]
    },
    "eslint.validate": [
        "javascript",
        "javascriptreact",
        {
            "language": "vue",
            "autoFix": true
        },
        "html",
        "vue"
    ],
